# Generated by Django 2.2.12 on 2020-05-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_instagram_instagram', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='plugin_template',
            field=models.CharField(choices=[('djangocms_instagram/default.html', 'Default')], default='djangocms_instagram/default.html', max_length=150, verbose_name='Design'),
        ),
    ]
