# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='headline',
            field=models.CharField(blank=True, default='Headline', help_text='Enter the headline for this plugin', max_length=150, verbose_name='Headline'),
        ),
        migrations.AddField(
            model_name='instagram',
            name='media_link_text',
            field=models.CharField(blank=True, default='See on Instagram', help_text='Enter the text for media link', max_length=50, verbose_name='Media link text'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_instagram_instagram', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='plugin_template',
            field=models.CharField(choices=[('djangocms_instagram/default.html', 'Default')], default='djangocms_instagram/default.html', max_length=150, verbose_name='Design'),
        ),
    ]
